exec-once = hyprpaper
exec-once = env LANG=es_MX.UTF-8 LC_ALL=es_MX.UTF-8 LC_TIME=es_MX.UTF-8 waybar
exec-once = gammastep -c ~/.config/gammastep/gammastep.conf
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hypridle
# exec-once = nm-applet
# exec-once = swaync
