$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
# $windows = rofi -show window
$windows = rofi -show window -window-thumbnail
$browser = firefox
$novelas = $HOME/.vn/vn_saves/script_menu.sh