# ===============================================
# Hyprland Appearance Configuration
# ===============================================

general {
    ### GAPS / ESPACIOS ###
    gaps_in = 1                  # Espacio entre ventanas
    gaps_out = 4,0,0,0          # Espacio entre ventanas y bordes del monitor (arriba, derecha, abajo, izquierda)

    ### BORDES ###
    border_size = 2       
    col.active_border   = 0xff2DD4BF   # aguamarina brillante
    col.inactive_border = 0xffA8A089   # café claro / beige

    ### INTERACCIÓN ###
    resize_on_border = false     # false = no puedes redimensionarww arrastrando desde el borde
                                 # true = puedes hacer clic y arrastrar el borde para redimensionar

    allow_tearing = false        # true = permite tearing gráfico (no recomendado)
                                 # false = evita tearing (recomendado para pantallas con vsync)

    ### DISEÑO ###
    layout = dwindle             # Tipo de distribución de ventanas (dwindle = en espiral estilo i3 dinámico)
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 5
    rounding_power = 5

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.8

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 5
        passes = 3
 	    ignore_opacity = true
    	new_optimizations = true
    	special = false
    	popups = true
    	xray = true
	
        vibrancy = 0.1696
    }
}


animations {
  enabled = no

  bezier = myBezier, 0.05, 0.9, 0.1, 1.05
  bezier = been, 0.24, 0.9, 0.25, 0.91
#   bezier = been2, 0,.94,.5,.99
  bezier = menu_decel, 0.1, 1, 0, 1
  bezier = linear, 0.0, 0.0, 1.0, 1.0
  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = slow, 0, 0.85, 0.3, 1
  bezier = overshot, 0.7, 0.6, 0.1, 1.1
  bezier = bounce, 1.1, 1.6, 0.1, 0.85
  bezier = sligshot, 1, -1, 0.15, 1.25
  bezier = nice, 0, 6.9, 0.5, -4.20
  
  animation = windowsIn, 1, 5, slow, popin
  animation = windowsOut, 1, 7, been, popin 70%
  animation = windowsMove, 1, 5, wind, slide
  animation = border, 1, 1, linear
  animation = fade, 1, 5, overshot
  animation = workspaces, 1, 5, wind
  animation = windows, 1, 5, bounce, popin
}


# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    vfr = true # save resources
}

render {
	new_render_scheduling = true
}
