# Monitor configuration
source = ~/.config/hypr/components/monitors.conf

# Programs desfinidos
source = ~/.config/hypr/components/programs.conf

# Comandos de arranque1
source= ~/.config/hypr/components/autostart.conf

# Variables de entorno
source = ~/.config/hypr/components/env.conf

# Appearance configuration
source = ~/.config/hypr/components/appearance.conf

# Input configuration
source = ~/.config/hypr/components/inputs.conf

# Atajos de teclado
source= ~/.config/hypr/components/keybinds.conf

# Window rules and workspace rules
source = ~/.config/hypr/components/windowrules.conf