splash = false
ipc = on

wallpaper {
    monitor = eDP-1
    path = $HOME/.hypr-files/wallpapers/green-sky.jpg
    fit_mode = cover
}

# fallback opcional (si conectas otro monitor después)
wallpaper {
    monitor =
    path = $HOME/.hypr-files/wallpapers/green-sky.jpg
    fit_mode = cover
}
preload = $HOME/.hypr-files/wallpapers/green-sky.jpg

# Monitor de la laptop
wallpaper = eDP-1,$HOME/.hypr-files/wallpapers/green-sky.jpg

# Monitor secundario (el fallback)
wallpaper = ,$HOME/.hypr-files/wallpapers/green-sky.jpg

splash = false
ipc = on