splash = false
ipc = on

wallpaper {
    monitor = eDP-1
    path = /home/nv/.dotfiles-hypr/wallpapers/green-sky.jpg
    fit_mode = cover
}

# fallback opcional (si conectas otro monitor después)
wallpaper {
    monitor =
    path = /home/nv/.dotfiles-hypr/wallpapers/green-sky.jpg
    fit_mode = cover
}
preload = /home/nv/.dotfiles-hypr/wallpapers/green-sky.jpg

# Monitor de la laptop
wallpaper = eDP-1,/home/nv/.dotfiles-hypr/wallpapers/green-sky.jpg

# Monitor secundario (el fallback)
wallpaper = ,/home/nv/.dotfiles-hypr/wallpapers/green-sky.jpg

splash = false
ipc = on