general {
    lock_cmd = hyprlock
    unlock_cmd = killall hyprlock
}

listener {
    timeout = 300          # 5 minutos
    on-timeout = hyprlock  # Bloquear pantalla
}

listener {
    timeout = 600          # 10 minutos
    on-timeout = hyprctl dispatch dpms off   # Apagar pantalla
    on-resume = hyprctl dispatch dpms on     # Encender pantalla
}

listener {
    timeout = 900          # 15 minutos
    on-timeout = systemctl suspend           # Suspender sistema
}