[profile]
name = "default"
description = "Primera receta de los dotfiles"

[designs]
fastfetch  = "default"
hypr       = "default"
hyprlock   = "default"
rofi       = "default"
starship   = "default"
swaync     = "default"
waybar     = "default"
wlogout    = "default"

[wallpaper]
path = "wallpapers/122252287_p0.jpg"