# --- [ FUENTES ] ---
font_family      JetBrainsMono NF Bold
font_size        12.0
bold_font        auto
italic_font      auto
bold_italic_font auto

# --- [ DISEÑO Y TRANSPARENCIA ] ---
background_opacity         0.9
confirm_os_window_close    0
window_padding_width       4
# Ocultar la barra de título decorativa (Hyprland ya maneja bordes)
hide_window_decorations    yes

# --- [ CURSOR ] ---
# Animated cursor (Trail)
cursor_trail             1
cursor_trail_decay       0.1 0.4
cursor_trail_start_threshold 2

# --- [ RENDIMIENTO (Optimizado T490/Wayland) ] ---
# Forzar Wayland para evitar borrosidad de XWayland
linux_display_server     wayland
# Minimizar latencia de entrada
repaint_delay            10
input_delay              3
sync_to_monitor          yes

# --- [ COMPORTAMIENTO ] ---
scrollback_lines         2000
wheel_scroll_min_lines   1
enable_audio_bell        no

# URLs
detect_urls              yes
url_style                curly
open_url_with            default

# --- [ PERFILES / TEMAS ] ---
# Este archivo será un symlink generado por tu script de perfiles
include current-theme.conf